name: build-push-databricksruntime-standard-degauss-geocoder:14.3-LTS

on:
  workflow_dispatch:
  push:
    branches: main
    paths: databricksruntime/standard/degauss-geocoder/14.3-LTS/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the-mad-statter/dockerfiles
        uses: actions/checkout@v4
      -
        name: Checkout degauss-org/geocoder
        uses: actions/checkout@v4
        with:
          repository: degauss-org/geocoder
          path: databricksruntime/standard/degauss-geocoder/14.3-LTS/geocoder
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: databricksruntime/standard/degauss-geocoder/14.3-LTS
          push: true
          tags: themadstatter/databricksruntime-standard-degauss-geocoder:14.3-LTS