name: build-push-washu-ris-rocker-tidyverse:4.0.2

on:
  workflow_dispatch:
  push:
    branches: main
    paths: washu-ris/rocker/tidyverse/4.0.2/Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the-mad-statter/dockerfiles
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}    
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: washu-ris/rocker/tidyverse/4.0.2
          push: true
          tags: themadstatter/washu-ris-rocker-tidyverse:4.0.2